name: OpenTypeless
options:
  bundleIdPrefix: com.opentypeless
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  OpenTypeless:
    type: application
    platform: macOS
    sources:
      - path: OpenTypeless
        excludes:
          - "**/.DS_Store"
    configFiles:
      Debug: Pods/Target Support Files/Pods-OpenTypeless/Pods-OpenTypeless.debug.xcconfig
      Release: Pods/Target Support Files/Pods-OpenTypeless/Pods-OpenTypeless.release.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.opentypeless.app
        INFOPLIST_FILE: OpenTypeless/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: OpenTypeless/Resources/OpenTypeless.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Menu bar app - don't show in dock
        INFOPLIST_KEY_LSUIElement: true
        # Bridging header for Azure Speech SDK
        SWIFT_OBJC_BRIDGING_HEADER: "OpenTypeless/Resources/OpenTypeless-Bridging-Header.h"
    info:
      path: OpenTypeless/Resources/Info.plist
      properties:
        LSUIElement: true
        NSMicrophoneUsageDescription: "OpenTypeless needs microphone access to transcribe your speech into text."
        NSSpeechRecognitionUsageDescription: "OpenTypeless needs speech recognition access to convert your speech into text."
    entitlements:
      path: OpenTypeless/Resources/OpenTypeless.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
    preBuildScripts:
      - name: "[CP] Check Pods Manifest.lock"
        script: |
          diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
          if [ $? != 0 ] ; then
              echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation."
              exit 1
          fi
        inputFiles:
          - ${PODS_PODFILE_DIR_PATH}/Podfile.lock
          - ${PODS_ROOT}/Manifest.lock
        outputFiles:
          - $(DERIVED_FILE_DIR)/Pods-OpenTypeless-checkManifestLockResult.txt
    postBuildScripts:
      - name: "[CP] Embed Pods Frameworks"
        script: |
          "${PODS_ROOT}/Target Support Files/Pods-OpenTypeless/Pods-OpenTypeless-frameworks.sh"
        inputFiles:
          - ${PODS_ROOT}/Target Support Files/Pods-OpenTypeless/Pods-OpenTypeless-frameworks.sh
          - ${BUILT_PRODUCTS_DIR}/MicrosoftCognitiveServicesSpeech.framework
        outputFiles:
          - ${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/MicrosoftCognitiveServicesSpeech.framework

schemes:
  OpenTypeless:
    build:
      targets:
        OpenTypeless: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
