name: OpenTypeless
options:
  bundleIdPrefix: com.opentypeless
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  OpenTypeless:
    type: application
    platform: macOS
    sources:
      - path: OpenTypeless
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.opentypeless.app
        INFOPLIST_FILE: OpenTypeless/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: OpenTypeless/Resources/OpenTypeless.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Menu bar app - don't show in dock
        INFOPLIST_KEY_LSUIElement: true
    info:
      path: OpenTypeless/Resources/Info.plist
      properties:
        LSUIElement: true
        NSMicrophoneUsageDescription: "OpenTypeless needs microphone access to transcribe your speech into text."
        NSSpeechRecognitionUsageDescription: "OpenTypeless needs speech recognition access to convert your speech into text."
    entitlements:
      path: OpenTypeless/Resources/OpenTypeless.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

schemes:
  OpenTypeless:
    build:
      targets:
        OpenTypeless: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
